### ISSUE TITLE
Waiting for device (Linux Mint 19.3.)

### ISSUE THREAD

**Issue by hoplik** [nijel8/emmcdl#3]
en.
Hi.
Can you help?
Running a compiled project in Linux Mint 19.3.
The compilation passed without errors. (photo 1)
Connecting the device in EDL mode.(photo 3)
Linux sees the device and puts it on the ttyUSB0 port(photo 4)
When requesting ./emmcdl -p ttyUSB0 -info or -gpt, the terminal waits for the device to connect, but it is already connected.(photo 5)
I think the program is waiting for some response from the device or something?
I tried to disable / connect the device while waiting, it doesn't help, it also hangs.
=====
ru.
Привет.
Сможете помочь?
Запускаю скомпилированный проект в Linux Mint 19.3.
Компиляция прошла без ошибок. (фото1)
Подключаю устройство в режиме EDL.(фото3)
Linux устройство видит и сажает на порт ttyUSB0(фото4)
При запросе ./emmcdl -p ttyUSB0 -info или -gpt терминал ждёт подключения устройства, но оно уже подключено.(фото5)
Думаю, программа ждёт какого-то ответа от устройства или ещё что-то?
Пробовал отключить/подключить устройство при этом ожидании. Не помогает, также висит.
![1](https://user-images.githubusercontent.com/60131631/79080774-73982e00-7d20-11ea-899a-fadbdf45dfc7.png)
![3](https://user-images.githubusercontent.com/60131631/79080775-7c88ff80-7d20-11ea-9daf-0dd5661e7556.png)
![4](https://user-images.githubusercontent.com/60131631/79080778-801c8680-7d20-11ea-8d5a-2d6416b86af8.png)
![5](https://user-images.githubusercontent.com/60131631/79080779-827ee080-7d20-11ea-8155-79d777d3bea8.png)

**Comment by totalolage** [comment]
I'm having a similar issue (on windows), any progeress?

**Comment by hoplik** [comment]
I did not manage to compile the project at all (In Windows10, under VS2019), but using a ready-made exe file, everything works successfully, without errors. I would like to have a working package for Linux.

**Comment by totalolage** [comment]
I'm trying to compile it now. Do you have a link to the exe you used? Or can you share it? (I'm using win 7 though)

**Comment by hoplik** [comment]
v2.16. for win.
[emmcdl_2_16.exe.zip](https://github.com/nijel8/emmcdl/files/4477656/emmcdl_2_16.exe.zip)

**Comment by totalolage** [comment]
Thank you very much, unfortunately the issue persists :(

(this is now running the executable you shared; same result)
![image](https://user-images.githubusercontent.com/41711263/79274267-9c493080-7ea4-11ea-8928-5c21794b172d.png)

**Comment by hoplik** [comment]
Driver not correct, i think. Device in EDL (emergency download) pid 9008. No any ! in com-port list.

**Comment by totalolage** [comment]
I tried reinstalling all drivers with no success.
I've now compiled emmcdl on linux and have the identical behaviour to what you had;
![image](https://user-images.githubusercontent.com/41711263/79319463-a56be900-7f08-11ea-9667-9cbe27434004.png)

Edit:
I put some debugging prints into the code and recompiled. A check on the device fails in the `match_fastboot_with_serial` function (in usbport.cpp). For some reason, my device reports a USB interface code of `0x10` when the tool expects `0xff`. These codes are vendor specific and I have so far not found what they mean.

**Comment by hoplik** [comment]
I think there is a problem with the USB port settings in Linux. Unfortunately, I can't find any information about what parameters I need to set for stable operations.

**Comment by spvkgn** [comment]
> I put some debugging prints into the code and recompiled. A check on the device fails in the `match_fastboot_with_serial` function (in usbport.cpp). For some reason, my device reports a USB interface code of `0x10` when the tool expects `0xff`. These codes are vendor specific and I have so far not found what they mean.

https://www.usb.org/defined-class-codes

I got `ff` codes in Class, SubClass and Protocol but same problem occurs.
```
$ sudo cat /sys/kernel/debug/usb/devices
…
T:  Bus=01 Lev=01 Prnt=01 Port=03 Cnt=02 Dev#=  7 Spd=480  MxCh= 0
D:  Ver= 2.00 Cls=00(>ifc ) Sub=00 Prot=00 MxPS=64 #Cfgs=  1
P:  Vendor=05c6 ProdID=9008 Rev= 0.00
S:  Manufacturer=Qualcomm CDMA Technologies MSM
S:  Product=QHSUSB__BULK
C:* #Ifs= 1 Cfg#= 1 Atr=80 MxPwr=  2mA
I:* If#= 0 Alt= 0 #EPs= 2 Cls=ff(vend.) Sub=ff Prot=ff Driver=qcserial
E:  Ad=81(I) Atr=02(Bulk) MxPS= 512 Ivl=0ms
E:  Ad=01(O) Atr=02(Bulk) MxPS= 512 Ivl=0ms
```

**Comment by hoplik** [comment]
In response to the code 
`sudo cat /sys/kernel/debug/usb/devices`
I get the same response about Vendor Specific Class Code
`T:  Bus=01 Lev=01 Prnt=01 Port=04 Cnt=02 Dev#=  5 Spd=480  MxCh= 0
D:  Ver= 2.00 Cls=00(>ifc ) Sub=00 Prot=00 MxPS=64 #Cfgs=  1
P:  Vendor=05c6 ProdID=9008 Rev= 0.00
S:  Manufacturer=Qualcomm CDMA Technologies MSM
S:  Product=QUSB__BULK
C:* #Ifs= 1 Cfg#= 1 Atr=a0 MxPwr=  2mA
I:* If#= 0 Alt= 0 #EPs= 2 Cls=ff(vend.) Sub=ff Prot=ff Driver=qcserial
E:  Ad=81(I) Atr=02(Bulk) MxPS= 512 Ivl=0ms
E:  Ad=01(O) Atr=02(Bulk) MxPS= 512 Ivl=0ms`

**Comment by spvkgn** [comment]
There is another fork https://github.com/ccz120/emmcdl , it works with ttyUSB but it seems there is a problem with gpt dump option. Other options not tested yet.

```
$ sudo ./emmcdl -p ttyUSB0 -info
Version 2.10
open serial port:/dev/ttyUSB0 succeed
Serial Port No data within five seconds. Success

===============Device Class:sahara Protocol:firehose Emergency:false================
Sahara version 1--2 
mode 3.
SerialNumber: 0x66f8b654
MSM_HW_ID: 0x0004f0e1
OEM_PK_HASH: 0xcab02552dc28f562e8c5befa75bc4a97b90aab1c91a3c186ec51f3d3d7d6a1c7
SBL SW Version: 0x00000000

Status: 0 Success

$ sudo ./emmcdl -p ttyUSB0 -f prog_emmc_firehose_8937_ddr.mbn -gpt
Version 2.10
open serial port:/dev/ttyUSB0 succeed
Serial Port No data within five seconds. Success
PblHack: Error - cmd:1836597052, status:824327534
Serial Port No data within five seconds. Resource temporarily unavailable
0: 0: 0: 0: 0: 0: 0: 0: 0: 0: 0: 0: 0: 0: 0: 0: 0: 0: 0: 0: 0: 0: 0: 0: 0: 0: 0: 0: 0: 0: 0: 0: 
Firehose:ConnectToFlashProg
Serial Port No data within five seconds. Resource temporarily unavailable
Serial Port No data within five seconds. Resource temporarily unavailable

===============Device Class:sahara Protocol:firehose Emergency:true================
Firehose:ConnectToFlashProg
Serial Port No data within five seconds. Resource temporarily unavailable
Serial Port No data within five seconds. Resource temporarily unavailable
Connected to flash programmer, starting download
Downloaded raw image at speed   0.6305 MB/s 00:00:02
Status: 0 Success
```

**Comment by hoplik** [comment]
Thank you for the link. I checked it on my phone, seems, all work good.
![Снимок экрана в 2020-10-07 22-26-27](https://user-images.githubusercontent.com/60131631/95378141-2a4e2300-08ec-11eb-9dfc-86ea429f151b.png)

**Comment by hoplik** [comment]
Closed

**Comment by ghost** [comment]
None of the options from the forked link above seem to work. Trying to dump partitions appears to work, but doesn't even actually do anything. This is really annoying since I don't want to resort to Windows just to use it
